### ISSUE TITLE
Create an alternate method for pagebreaks to account for alternate use cases.

### ISSUE THREAD

**Issue by MrFarland** [encounterplus/module-packer#15]
The current method of creating page breaks based on heading is a great feature, but it has some drawbacks that are not easily worked around. The problem arises when you want to pagebreak for organizational reasons, but do not necessarily want to change the heading style. 

The Campaign Manager module I am working on makes good use of the pagebreak feature for the geography pages like so:

continent.md
Continent (H1)
Continent/Region (H2)
Continent/Region/Feature (H3)
Continent/Region/Roads (H3)
Continent/Region/Settlements (H3)

For this to work, the styles for the H1, H2, H3 are all the same. H4, H5, and H6 are then used on pages to break up content without pagebreaks. This approach works well enough if the content is relatively static and isn't going to be changed by users very often. It causes problems though, if some pages in the module are intended to be edited regularly. Users expect to use headings in descending order and would not expect to find the H2 looks the same as the H1.

I believe we need an alternate method for creating pagebreaks in the source markdown. Based on some basic research, it would seem that Markdown does not have a native syntax for inserting a pagebreak, but perhaps we could create our own implementation using styles. I'm thinking we could use the syntax for a horizontal rule and add styles for the following scenarios:

```
---
<!-- {hr: .pagebreak} -->
```
Inserts a simple pagebreak that does not automatically nest. The next pages is created at the same level as the previous page.

```
---
<!-- {hr: .pagebreak, .nest} -->
```
Inserts a pagebreak that automatically places the following page under the previous page. (I'm not sure of the proper syntax for multiple styles.)

An approach like this would eliminate the issue described above as well as the issue of pagebreaks for the print to PDF feature. I'm not sure if this would affect the cover image styles.

**Comment by jacobjohnston** [comment]
I've been giving this some consideration - and have added a lot of infrastructure to make custom tags a bit more approachable now. I'm thinking I would use the syntax style I already have for print-page breaks (i.e., `(print-page)`). I'm thinking I would allow `(module-page)` and `(module-page-nest)`. I'm not quite sure how to handle the nesting situation like this, however.

Page A (Root Level)
-- Page B (Level 1)
---- Page C (Level 2)
-- Page D (Level 1)

I need some way to de-nest, and I'm not sure what sort of syntax makes sense there. Open to suggestions.

**Comment by jacobjohnston** [comment]
While not exactly what is proposed, there is now an alternate way to Nest pages. A parent-page attribute can be added to the front-matter of a markdown file. For the value, specify the slug of the page you want to nest under. Currently, this cannot be combined with pagebreaks (that value will be ignored if parent-page is specified).

**Comment by MrFarland** [comment]
I just noticed this is still hanging out there, but felt that the new approach works well.
