### ISSUE TITLE
The Name and Slug page settings are not used when creating pages.

### ISSUE THREAD

**Issue by MrFarland** [encounterplus/module-packer#34]
When creating entries in module.xml for pages, the packer is using the filename to create the name and slug for the page. The Name and Slug specified in the markdown header are not used.

When creating a file for the 'Alabaster Sierras' region on the continent of Tal'Dorei, I created a file called 'taldorei_region_alabaster-sierras.md' to help keep the vast number of pages nominally organized. After the build, I checked the XML and noticed the following.

<name>taldorei_region_alabaster-sierras.md</name>
<slug>taldoreiregionalabaster-sierrasmd</slug>

It doesn't look like the name and slug are being used at all.

**Comment by jacobjohnston** [comment]
Fixed
