### ISSUE TITLE
Sub-pages are not getting their sort attribute set.

### ISSUE THREAD

**Issue by stickystyle** [encounterplus/module-packer#35]
The `<page>` elements are in the correct order in the `module.xml` file, but when you import into E+, everything is reversed.

https://discord.com/channels/565243968858751027/647438059226529807/763070356814299206

![Screen Shot 2020-10-06 at 9 38 14 AM](https://user-images.githubusercontent.com/858414/95232208-2cbc5a00-07d2-11eb-8d5d-c1b3325ecead.png)

![Screen Shot 2020-10-06 at 9 39 23 AM](https://user-images.githubusercontent.com/858414/95232226-334ad180-07d2-11eb-9d28-4773ea44b2bd.png)

Sample project that generates a module in this state.
[First Blush.zip](https://github.com/encounterplus/module-packer/files/5335366/First.Blush.zip)

**Comment by jacobjohnston** [comment]
Will be fixed in the 1.0.18 release
