### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by HTML-CODDER** [encounterplus/module-packer#39]
- Issue Type: `Performance`
- Extension Name: `encounterplus-markdown`
- Extension Version: `1.0.21`
- OS Version: `Darwin x64 17.7.0`
- VSCode version: `1.51.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/var/folders/gf/svw259c16zsfjz5245qg5n300000gp/T/jacobjohnston.encounterplus-markdown-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by jacobjohnston** [comment]
@HTML-CODDER Would you mind attaching the file that mentions. It'll help me narrow down which bit of code might be spinning your CPU so I can optimize.

**Comment by jacobjohnston** [comment]
Closing this issue without more information. The extension was changed to use web pack where possible, and as such, should have faster load times.
