### ISSUE TITLE
Ability to hide a group but process pages.

### ISSUE THREAD

**Issue by MrFarland** [encounterplus/module-packer#42]
**Request**
Add a option called "hidden" a group to the "include-in" directive in a group.yaml to process and include any pages inside the group, but not display the group in the module.

**Requirements**
- Any page contained within the folder must have a "parent" defined in the page header to be accessible in the module.

**Use Case**
When working with large numbers of pages, it is helpful to be able to use folders to better organize the files but retain the ability to use another page as the parent to those pages.

For example: My DM screen module has nearly 300 pages with many more to come. The UI will basically look like:

- Home
- Abilities
  - Strength
  - Dexterity
- Combat
  - Actions
     - Attack
     - Cast Spell
- Conditions
  - Blinded
  - Deafened

Being able to put files into folders based on their top level menu (conditions, abilities, etc) would greatly reduce the clutter in the module's root directory and make it easier to maintain.

**Comment by rrgeorge** [comment]
I think this is resolved with `remove-empty-groups: true`, right?

**Comment by jacobjohnston** [comment]
`delete-empty-groups: true`, but yes!

**Comment by rrgeorge** [comment]
> `delete-empty-groups: true`, but yes!

Release notes says `remove-empty-groups: true`

**Comment by jacobjohnston** [comment]
Oops, that was a mistake. `delete-empty-groups` is correct and I've updated the release notes
