### ISSUE TITLE
Feature Request: Publish vscode extension in OpenVSX

### ISSUE THREAD

**Issue by rrgeorge** [encounterplus/module-packer#44]
Code-server is not allowed to use the Microsoft extension marketplace, so it instead uses [OpenVSX](https://open-vsx.org/). It would be great if the vscode extension could be published there too, so that it can automatically receive updates on code-server.

**Comment by jacobjohnston** [comment]
The Visual Studio Code extension can now be found on OpenVSX:
https://open-vsx.org/extension/jacobjohnston/encounterplus-markdown
