### ISSUE TITLE
Generate PDFs in A4

### ISSUE THREAD

**Issue by chrisgb-dev** [encounterplus/module-packer#45]
For those of us outside the US, can we have the option to export PDFs in A4 format (210 x 297 mm) as an alternative to US-Letter?

**Comment by jacobjohnston** [comment]
I was wondering when someone would request this 😉. It's totally doable but is a bit of work, but I'll work on it. It'll be a preference you define in the Module.yaml file.

**Comment by chrisgb-dev** [comment]
Making it a YAML preference would be perfect - thanks!

**Comment by jacobjohnston** [comment]
Done! It can be accessed with the new `print-document-size` property.
