### ISSUE TITLE
Absolute image paths should be prefixed with "." not the current directory

### ISSUE THREAD

**Issue by rrgeorge** [encounterplus/module-packer#50]
Absolute image paths should be prefixed with "." not the current directory

**Comment by cffs** [comment]
`.` denotes the current directory, so prefixing *absolute* paths with it would be pretty strange. What is the problem exactly?

**Comment by rrgeorge** [comment]
Because absolute paths won’t work when loaded into E+, since the module is actually under `/module/<id>/`. 
But when using an absolute path for proper rendering in VSCode, the root is the root of the module.
