### ISSUE TITLE
Enhancement: Spells

### ISSUE THREAD

**Issue by PiSaucer** [encounterplus/module-packer#52]
I was writing spells in modules and noticed that it doesn't support markdown in the app. It would be greatly appreciated if they had markdown/html support in the descriptions of the spell. As of now, they work fine for PDF generation.

---

PDF:
![mage-hand-pdf](https://user-images.githubusercontent.com/33438654/147163439-ab0208c2-375e-4e78-b874-d3815b7ad383.png)

App: 
![mage-hand-app](https://user-images.githubusercontent.com/33438654/147163458-8b4e6c13-f8bb-4e00-bc98-91646a57fb96.jpg)

**Comment by PiSaucer** [comment]
@jacobjohnston Any updates to this enhancement? I would love to use this for my future campaigns.

**Comment by jacobjohnston** [comment]
Hey @PiSaucer 
1.) The proper way to do this is to not use `<br>` tags, but instead, use multiline strings in YAML. That should look like this (be aware of the indentation and extra lines added):
```YAML
description: "This legendary quarterstaff has thwacked many a foe.


    This is a multiline item
    
    
    More lines"
```

2.) The request, as written, requires a change to EncounterPlus itself, which I don't have the power to make.

**Comment by PiSaucer** [comment]
The multiline strings in YAML work in the PDF and the app. Thank you for your time and help. Do you have any idea if YAML could hold bold text?

**Comment by PiSaucer** [comment]
It turns out that the app supports `<b></b>` and `<i></i>` tags for bolding and italicize. However, it doesn't support both at once. Again, thank you for your time and help.
