### ISSUE TITLE
[Request] Add support for custom image sizes

### ISSUE THREAD

**Issue by AceDetectivePuff** [encounterplus/module-packer#6]
Markdown example:

```markdown
![Image Caption](/image/location.png width=500 height=100)
```

That's the standard for setting the max-width to be 500, and the max-height to be 100. If either of those values are unset, the default is "auto". If both are set, then the image resizes to fit both values.

**Comment by jacobjohnston** [comment]
This has now been implemented in 0.9.3 :-)

The readme now explains the use under the "Images" section.
